In [51]:
import numpy as np
from sklearn import preprocessing as p

In [52]:
data = np.array([[1.,-1.,2.],
                [2.,0.,0.],
                [0.,1.,-1.]])

### SCALING USING SCALE()

In [53]:
data_scaled1 = p.scale(data)

In [54]:
print(data_scaled1)
print(data_scaled1.mean(axis = 0))
print(data_scaled1.std(axis = 0))

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
[0. 0. 0.]
[1. 1. 1.]


### FEATURE SCALING FOR TRAINING DATA

In [55]:
scaler = p.StandardScaler()
data_scaled2 = scaler.fit(data)
data_scaled2.transform(data)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

### FEATURE SCALING FOR TESTING DATA

In [57]:
data_test = [[1,1,0]]
scaler.transform(data_test)

array([[ 0.        ,  1.22474487, -0.26726124]])